default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: blogapp
  pool: 5
  host: localhost
  username: postgres
  password: root

production:
  <<: *default
  database: blog_production
  username: postgres
  password: root